sonar.projectKey=AnastasiaYakushina_php-project-57
sonar.organization=anastasiayakushina

sonar.sources=app,routes,resources/views

sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**, node_modules/**, public/**, storage/**, database/**

